// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qcllkkkbgtieirwqayxn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFjbGxra2tiZ3RpZWlyd3FheXhuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5NjY1NjcsImV4cCI6MjA2NzU0MjU2N30.i9TNfaMcUocsMYYBElCf_UvByq8x2QDy-A30bJQN4k8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});